// fccoussahers/src/components/Footer.vue
<template>
    <footer class="footer">
        <div class="footer-container">
            <div class="footer-section">
                <h4>Contactez-nous</h4>
                <p>
                    Adresse : 17 Rue du Château, 09100 Les Pujols <br>
                    Ville : Les Pujols<br>
                    Téléphone : 05 61 68 71 44<br>
                    Email : 581747@footoccitanie.fr
                </p>
            </div>
            <div class="footer-section links">
                <h4>Liens utiles</h4>
                <div class="links-columns">
                    <ul>
                        <li><a target="_blank" class="nav-link" href="https://ariegefoot.fff.fr/">
                            <img class="logo" src="../assets/district_ariege.webp" alt="District de l'Ariège" /> 
                            District de l'Ariège
                        </a></li>
                        <li><a target="_blank" class="nav-link" href="https://occitanie.fff.fr/">
                            <img class="logo" src="../assets/Ligue_de_Football_d'Occitanie.webp" alt="Ligue d'Occitanie" /> 
                            Ligue d'Occitanie
                        </a></li>
                    </ul>
                    <ul>
                        <li><a target="_blank" class="nav-link" href="https://lespujols.fr/">
                            <img class="logo" src="../assets/mairie_pujol.webp" alt="Mairie des Pujols" /> 
                            Mairie des Pujols
                        </a></li>
                        <li><a target="_blank" class="nav-link" href="http://www.mairie-coussa.fr/">
                            <img class="logo" src="../assets/mairie_coussa.webp" alt="Mairie de Coussa" /> 
                            Mairie de Coussa
                        </a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
</template>


<script>
export default {
    name: 'Footer',
    // Add your component logic here
}
</script>

<style lang="scss" scoped>

.footer {
    background-color: #000; /* Couleur identique au header */
    color: #fff;
    padding: 20px;
    position: absolute; /* Permet de coller au bas */
    bottom: 0;
    left: 0;
    width: 100%;
}

.footer-container {
    display: flex;
    justify-content: space-between;
    flex-wrap: wrap;
    max-width: 1140px; /* Centrer avec une largeur fixe */
    margin: 0 auto;
    padding: 0 20px;
}

.footer-section {
    flex: 1;
    min-width: 300px; /* Ajuste la taille minimale */
    margin-bottom: 20px;
}

.links-columns {
    display: flex;
    justify-content: space-between;
}

.links ul {
    list-style: none;
    padding: 0;
    margin: 0;
}

.links ul li {
    margin-bottom: 10px;
}

.nav-link {
    text-decoration: none;
    color: #fff;
    font-weight: 500;
    display: flex;
    align-items: center;
    transition: color 0.3s;
}

.nav-link:hover {
    color: #00afea; /* Ajoute un effet de survol */
}

.logo {
    display: inline-block;
    height: 30px; /* Taille des logos */
    margin-right: 10px;
    vertical-align: middle;
}

</style>

// fccoussahers/src/components/Layout/Footer.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { Mail, Phone, MapPin } from 'lucide-react';
const Footer: React.FC = () => {
  return <footer className="bg-green-800 text-white">
      <div className="container mx-auto px-4 py-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Club Info */}
          <div>
            <h3 className="text-xl font-bold mb-4">FC Coussa Hers</h3>
            <div className="flex items-center mb-3">
              <MapPin size={18} className="mr-2" />
              <span>17 Rue du Château, 09100 Les Pujols</span>
            </div>
            <div className="flex items-center mb-3">
              <Phone size={18} className="mr-2" />
              <span>05 61 68 71 44</span>
            </div>
            <div className="flex items-center">
              <Mail size={18} className="mr-2" />
              <span>581747@footoccitanie.fr</span>
            </div>
          </div>
          {/* Quick Links */}
          <div>
            <h3 className="text-xl font-bold mb-4">Liens rapides</h3>
            <ul className="space-y-2">
              <li>
                <Link to="/" className="hover:underline">
                  Accueil
                </Link>
              </li>
              <li>
                <Link to="/club" className="hover:underline">
                  Le Club
                </Link>
              </li>
              <li>
                <Link to="/equipes" className="hover:underline">
                  Équipes
                </Link>
              </li>
              <li>
                <Link to="/partenaires" className="hover:underline">
                  Partenaires
                </Link>
              </li>
              <li>
                <a href="https://example.com/boutique" target="_blank" rel="noopener noreferrer" className="hover:underline">
                  Boutique
                </a>
              </li>
            </ul>
          </div>
          {/* Social & Legal */}
          <div>
            <h3 className="text-xl font-bold mb-4">Affiliations</h3>
            <div className="flex flex-wrap gap-4 mb-6">
              <a href="https://ariege.fff.fr/" target="_blank" rel="noopener noreferrer" className="block">
                <img src="/district_ariege.webp" alt="District Ariège FFF" className="h-12 bg-white p-1 rounded" />
              </a>
              <a href="https://occitanie.fff.fr/" target="_blank" rel="noopener noreferrer" className="block">
                <img src="/Ligue_de_Football_dOccitanie.svg" alt="Ligue de Football d'Occitanie" className="h-12 bg-white p-1 rounded" />
              </a>
            </div>
            <h4 className="font-semibold mb-2">Suivez-nous</h4>
            <a href="https://facebook.com" target="_blank" rel="noopener noreferrer" className="inline-flex items-center hover:underline mb-4">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" className="mr-2">
                <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path>
              </svg>
              Facebook
            </a>
          </div>
        </div>
        <div className="border-t border-green-700 mt-8 pt-6 text-center text-sm">
          <p>
            © {new Date().getFullYear()} FC Coussa Hers. Tous droits réservés.
          </p>
        </div>
      </div>
    </footer>;
};
export default Footer;
